#!/usr/bin/env python3
"""
Debug script for integration testing
This will compile and run the integration test with more detailed output
"""

import sys
import os
from pathlib import Path

# Add the necessary path for imports
sys.path.append('/Users/jithinpothireddy/Downloads/English Programming')
from english_programming.src.compiler.improved_nlp_compiler import ImprovedNLPCompiler
from english_programming.src.vm.improved_nlvm import ImprovedNLVM

def main():
    # Define files
    input_file = "/Users/jithinpothireddy/Downloads/English Programming/integrated_test.nl"
    output_file = "/Users/jithinpothireddy/Downloads/English Programming/integrated_test.debug.nlc"
    
    print("\n=== DEBUGGING INTEGRATION TEST ===")
    print(f"Source file: {input_file}")
    print(f"Output file: {output_file}")
    
    # First, let's display the source
    print("\n=== SOURCE CODE ===")
    with open(input_file, "r") as f:
        print(f.read())
    
    # Compile with detailed debugging
    print("\n=== COMPILATION PROCESS ===")
    compiler = ImprovedNLPCompiler()
    compiler.compile(input_file, output_file)
    
    # Display the compiled bytecode
    print("\n=== GENERATED BYTECODE ===")
    with open(output_file, "r") as f:
        bytecode = f.readlines()
        for i, line in enumerate(bytecode):
            print(f"{i}: {line.strip()}")
    
    # Execute with detailed debugging
    print("\n=== EXECUTION PROCESS ===")
    vm = ImprovedNLVM()
    result = vm.execute(output_file)
    
    print("\n=== EXECUTION ENVIRONMENT ===")
    print(vm.env)
    
    print("\n=== DEBUG COMPLETE ===")

if __name__ == "__main__":
    main()
