services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: hlx-web
    restart: always
    environment:
      - FLASK_APP=english_programming/src/interfaces/web/web_app.py
      - EP_ALLOW_NET=1
    ports:
      - "5000:5000"
networks:
  default:
    name: hlx-net

