name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt || true
      - run: python -m pip install pytest
      - run: PYTHONUNBUFFERED=1 pytest -q

name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[nlp,jit]'
          python -m pip install pytest
      - name: Run tests
        run: |
          pytest -q
      - name: Run benchmarks (jit tier 3)
        env:
          EP_JIT_TIER: '3'
        run: |
          python english_programming/benchmarks/run_benchmarks.py > bench_core.txt
          python english_programming/benchmarks/run_external.py > bench_external.txt || true
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epl-benchmarks
          path: |
            bench_core.txt
            bench_external.txt
